FROM postgres:16.3

# Set environment variables for the database
ENV POSTGRES_DB=parking_control_db
ENV POSTGRES_USER=clean
ENV POSTGRES_PASSWORD=database

# Expose the default PostgreSQL port
EXPOSE 5432

# Run the PostgreSQL server
CMD ["postgres"]